name: launch_review
description: A Flutter plugin to assist in leaving user reviews/ratings in Google Play Store and Apple App Store.
version: 3.0.1
homepage: https://github.com/purus/launch_review/

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ^3.5.4
